# Generated by Django 3.2.8 on 2021-11-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fleet_managers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, default=0, null=True)),
                ('pressure', models.FloatField(blank=True, default=0, null=True)),
                ('remaning_battery', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'WORKING'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER'), ('LOST', 'LOST'), ('BROKEN', 'BROKEN')], default='ACTIVE', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('remaining_life', models.IntegerField(blank=True, null=True)),
                ('baseline_pressure', models.IntegerField(blank=True, null=True)),
                ('fill_material', models.CharField(blank=True, max_length=30, null=True)),
                ('tread_depth', models.IntegerField(blank=True, null=True)),
                ('revolutions', models.IntegerField(blank=True, null=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('ambient_temperature', models.IntegerField(blank=True, null=True)),
                ('distance_driven', models.IntegerField(blank=True, null=True)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('consumed_fuel', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('machine_hours', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpms.company')),
                ('tires', models.ManyToManyField(blank=True, to='tpms.Tire')),
            ],
        ),
    ]
