# Generated by Django 3.2.8 on 2021-12-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms', '0002_auto_20211217_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k1',
            name='id',
        ),
        migrations.AlterField(
            model_name='k1',
            name='distance',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
