# Generated by Django 3.2.8 on 2021-12-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('remaning_battery', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'WORKING'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER'), ('LOST', 'LOST'), ('BROKEN', 'BROKEN')], default='WORKING', max_length=30, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.company')),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('remaining_life', models.FloatField(blank=True, null=True)),
                ('baseline_pressure', models.FloatField(blank=True, null=True)),
                ('fill_material', models.CharField(blank=True, max_length=30, null=True)),
                ('tread_depth', models.FloatField(blank=True, null=True)),
                ('revolutions', models.FloatField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.company')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('ambient_temperature', models.FloatField(blank=True, null=True)),
                ('consumed_fuel', models.FloatField(blank=True, null=True)),
                ('distance_driven_empty', models.FloatField(blank=True, null=True)),
                ('distance_driven_loaded', models.FloatField(blank=True, null=True)),
                ('machine_hours_empty', models.IntegerField(blank=True, null=True)),
                ('machine_hours_loaded', models.IntegerField(blank=True, null=True)),
                ('payload_empty', models.FloatField(blank=True, null=True)),
                ('payload_loaded', models.FloatField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.company')),
                ('locations', models.ManyToManyField(blank=True, to='tpms.Location')),
                ('tires', models.ManyToManyField(blank=True, to='tpms.Tire')),
            ],
        ),
        migrations.CreateModel(
            name='FleetManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpms.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
