# Generated by Django 3.2.8 on 2021-12-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_specc',
            field=models.CharField(blank=True, choices=[('NEUTRAL', 'NEUTRAL'), ('OVER', 'OVER'), ('UNDER', 'UNDER')], max_length=30, null=True),
        ),
    ]
