# Generated by Django 3.2.8 on 2021-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms', '0002_auto_20211209_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadministrator',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fleetmanager',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
