# Generated by Django 3.2.8 on 2021-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms', '0003_auto_20211217_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='payload_empty',
            new_name='payload',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='payload_loaded',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='buckets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tkph',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
