# Generated by Django 3.2.8 on 2021-12-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms', '0004_auto_20211225_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_used',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='is_used',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
